### ISSUE TITLE
no network, then can't write newick format

### ISSUE THREAD

**Issue by cecileane** [jjustison/SiPhyNetwork#3]
## 1. empty network

Here is a small example where I get nothing simulated:

```r
require(SiPhyNetwork)
inheritance_fxn = make.beta.draw(10,10)
hybridproportions = c(0.5,0.25,0.25)
set.seed(1234)
net <- sim.bdh.taxa.ssa(n=7, numbsim=1,
    lambda=1,mu=0.2,
    nu=0.20, hybprops=hybridproportions,
    hyb.inher.fxn = inheritance_fxn)
net
```

and `net` is empty:

```
[[1]]
[1] 0
```

But: if I give `n=7L` instead of `n=7`, then it works:
```r
net <- sim.bdh.taxa.ssa(n=7L, numbsim=1,
    lambda=1,mu=0.2,
    nu=0.20, hybprops=hybridproportions,
    hyb.inher.fxn = inheritance_fxn)
net
```

```
[[1]]
$edge
      [,1] [,2]
 [1,]    9   10
 [2,]   10   11
...
```

## 2. can't write newick

but then... I can't get the parenthetical description of the network:

```r
write.net(net[[1]])
```

```
Error: $ operator is invalid for atomic vectors
```

Sorry, I should have probably opened 2 separate issues. I am eager to use your package!! :smiley:

**Comment by jjustison** [comment]
As for the first issue, I would suspect `net` is empty on the first simulation because the phylogeny went extinct before the reaching 7 species and was able to finish on the second run. Instead of returning a phylogeny, the simulator should return 0 when the phylogeny goes extinct before the desired time/number of tips and should return a 1 when there is only one extant tip left (although there are a few edge cases I've found where 1 tipped phylogenies get returned).

In the example given, I think it is a RNG thing than a difference between using `7` and `7L` as I was able to get the same output for both cases. It looks like the difference comes from not resetting the seed.

**Using n=7**
```
set.seed(1234)
net <- sim.bdh.taxa.ssa(n=7, numbsim=1,
                        lambda=1,mu=0.2,
                        nu=0.20, hybprops=hybridproportions,
                        hyb.inher.fxn = inheritance_fxn)
net
```
```
[[1]]
[1] 0
```
```
##Running the same code again without resetting the seed
net <- sim.bdh.taxa.ssa(n=7, numbsim=1,
                        lambda=1,mu=0.2,
                        nu=0.20, hybprops=hybridproportions,
                        hyb.inher.fxn = inheritance_fxn)
net
```  

```
[[1]]
$edge
      [,1] [,2]
 [1,]    9   10
 [2,]   10   11
...
```


**Using n=7L**
```
set.seed(1234)
net <- sim.bdh.taxa.ssa(n=7L, numbsim=1,
                        lambda=1,mu=0.2,
                        nu=0.20, hybprops=hybridproportions,
                        hyb.inher.fxn = inheritance_fxn)
net
```
```
[[1]]
[1] 0
```
```
##Running the same code again without resetting the seed
net <- sim.bdh.taxa.ssa(n=7L, numbsim=1,
                        lambda=1,mu=0.2,
                        nu=0.20, hybprops=hybridproportions,
                        hyb.inher.fxn = inheritance_fxn)
net
```  

```
[[1]]
$edge
      [,1] [,2]
 [1,]    9   10
 [2,]   10   11
...
```
Have you encountered other cases where using a numeric gives a different output than an integer?

**Comment by jjustison** [comment]
For the second issue, I tried loading `ape` beforehand it fixed things.  It should be a dependency but it doesn't seem to load, I will fix this.

**Using the `net` from above**
```
##install.packes('ape')
library('ape)
write.net(net[[1])
```
```
[1] "((((t7:0.4965063388,(t2:0.2047263165,(t8:0.09074681744,(t6:0.01933638066,t5:0.01933638066):0.07141043678):0.1139794991):0.2917800222):0.2284754762,t1:0.7249818149):0.6462898213,(t4:1.243514899,t3:0.1962098845):0.1277567371):0.2338510088);"
```

Sorry for the bugs but thanks for trying it out and helping me improve it!

**Comment by cecileane** [comment]
Beautiful!! I thought that I had reset the seed, but obviously not. Thanks a bunch!!
